- name: Download Golang tarball
  get_url:
    url: "https://dl.google.com/go/go{{ go_version }}.linux-{{ GOARCH }}.tar.gz"
    dest: /tmp/
- name: Untar Golang
  shell: "tar -C {{ go_install_folder }} -xzf /tmp/go{{ go_version }}.linux-{{ GOARCH }}.tar.gz"
- name: "Create /etc/profile.d/{{ user_name }}.sh"
  shell: "touch /etc/profile.d/{{ user_name }}.sh"
- name: Add to $HOME/.profile
  shell: "echo 'PATH=$PATH:{{ go_install_folder }}/go/bin' >> /etc/profile.d/{{ user_name }}.sh"
- name: Export GOARCH
  shell: "echo 'export GOARCH={{ GOARCH }}' >> /etc/profile.d/{{ user_name }}.sh"
- name: Export GOOS
  shell: "echo 'export GOOS={{ GOOS }}' >> /etc/profile.d/{{ user_name }}.sh"
- name: Export GO111MODULE
  shell: "echo 'export GO111MODULE={{ GO111MODULE }}' >> /etc/profile.d/{{ user_name }}.sh"
- name: Export GOROOT
  shell: "echo 'export GOROOT={{ GOROOT }}' >> /etc/profile.d/{{ user_name }}.sh"
- name: Export GOPATH
  shell: "echo 'export GOPATH={{ GOPATH }}' >> /etc/profile.d/{{ user_name }}.sh"
