- hosts: localhost
  become: yes
# TODO: install my ssh keys
  pre_tasks:
    - name: Include LinuxMint pre tasks
      include_tasks: tasks/setup-pre-tasks-mint.yml
      when: ansible_distribution == "LinuxMint"
  post_tasks:
    - name: Include LinuxMint post tasks
      include_tasks: tasks/setup-post-tasks-mint.yml
      when: ansible_distribution == "Ubuntu"
  vars_files:
  - vars/common.yml
  - vars/docker.yml
  - vars/maven.yml
  - vars/java.yml
  - vars/go.yml
  - vars/terraform.yml
  roles:
  - geerlingguy.java
  - geerlingguy.docker
  - tecris.maven
  - gantsign.visual-studio-code
  - cmprescott.chrome
  - golang
  - protobuf
  - protobuf-go
  - terraform
  tasks:
    - name: Include main tasks
      include_tasks: tasks/main.yml
