- hosts: all


# TODO: clone update golang repo
# TODO: install my ssh keys
# TODO: clone configs repository

roles:
  - geerlingguy.java #
  - geerlingguy.docker #
  - tecris.maven #
  - gantsign.visual-studio-code
  - cmprescott.chrome #
  - fubarhouse.golang #
  - kbrebanov.openvpn
  - fubarhouse.rust #
  - protobuf
  - protobuf-go
  - terraform

tasks:
- name: Create directories
  file:
    path: "/home/yannic/{{ item }}"
    state: directory    
    owner: yannic
    group: yannic
  with_items:
    - ["go", "java", "rust", "cpp", "volix", "rewinside", "misc"]
