- hosts: localhost
  become: yes
  # Whe have to add these pre and post tasks for Linux Mint because
  # some roles will not work since ansible_distribution will return
  # 'Linux Minut' instead of 'Ubuntu' which causes wrong apt repo entries.
  pre_tasks:
    - name: Include LinuxMint pre tasks
      include_tasks: tasks/setup-pre-tasks-mint.yml
      when: ansible_distribution == "LinuxMint"
  post_tasks:
    - name: Include LinuxMint post tasks
      include_tasks: tasks/setup-post-tasks-mint.yml
      when: ansible_distribution == "Ubuntu"
  vars_files:
  - vars/common.yml
  - vars/docker.yml
  - vars/maven.yml
  - vars/java.yml
  - vars/go.yml
  - vars/terraform.yml
  - vars/kind.yml
  roles:
  - geerlingguy.java
  - geerlingguy.docker
  - tecris.maven
  - gantsign.visual-studio-code
  - cmprescott.chrome
  - golang
  - protobuf
  - protobuf-go
  - terraform
  - kind
  - twirp
  tasks:
    - name: Include main tasks
      include_tasks: tasks/main.yml
# TODO: install my ssh keys
