- hosts: localhost
  become: yes
  vars_files:
  - vars/common.yml
  - vars/docker.yml
  - vars/maven.yml
  - vars/java.yml
  - vars/go.yml
  - vars/terraform.yml
  - vars/kind.yml
  roles:
  - geerlingguy.java
  - geerlingguy.docker
  - tecris.maven
  - gantsign.visual-studio-code
  - cmprescott.chrome
  - golang
  - protobuf
  - protobuf-go
  - terraform
  - kind
  - twirp
  tasks:
    - name: Include main tasks
      include_tasks: tasks/main.yml
# TODO: install my ssh keys
