- hosts: localhost

# TODO: install my ssh keys
  pre_tasks:
  - name: Backup /etc/lsb-release file
    shell: mv /etc/lsb-release /etc/lsb-release.orig
    when: conditon
  - name: Copy new /etc/lsb-release file
    copy:
       src: config/lsb-release
       dest: /etc/lsb-release
  - name: Backup /etc/os-release
    shell: mv /etc/os-release /etc/os-release.orig
  - name: Copy new /etc/os-release file
    copy:
      src: config/os-release
      dest: /etc/os-release

  vars_files:
  - vars/common.yml
  - vars/docker.yml
  - vars/maven.yml
  - vars/java.yml
  - vars/go.yml
  - vars/terraform.yml
  roles:
  - geerlingguy.java
  - geerlingguy.docker
  - tecris.maven
  - gantsign.visual-studio-code
  - cmprescott.chrome
  - golang
  - protobuf
  - protobuf-go
  - terraform
  tasks:
  - name: Create directories
    file:
      path: "/home/{{ user_name }}/workspace/{{ item }}"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
    with_items:
      - ["go", "java", "rust", "cpp", "volix", "rewinside", "misc"]
  
  #- name: Download SSH keys
    #get_url:
      #url: /some/url/{{ item }}
      #dest: "/home/yannic/.ssh/{{ item }}"
    #with_items:
      #- [""] # TODO: private SSH keys
      #- [""] # TODO: public SSH keys

  - name: Clone Update Golang repository
    git:
      repo: https://github.com/udhos/update-golang.git
      dest: "/home/{{ user_name }}/workspace/misc/update-golang"

  - name: Clone repository containing personal configs
    git:
      repo: git@github.com:Freggy/configs.git
      dest: "/home/{{ user_name }}/workspace/misc/configs"
