- name: Backup /etc/lsb-release file
  shell: mv /etc/lsb-release /etc/lsb-release.orig
- name: Copy new /etc/lsb-release file
  shell: rm /etc/lsb-release && cp config/lsb-release /etc/lsb-release
- name: Backup /usr/lib/os-release
  shell: cp /usr/lib/os-release /usr/lib/os-release.orig
- name: Copy new /usr/lib/os-release file
  copy:
    src: config/os-release
    dest: /usr/lib/os-release
